// <auto-generated />
using System;
using GameServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameServer.PlayerDb", b =>
                {
                    b.Property<int>("PlayerDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerDbId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PlayerDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GameServer.RoomDb", b =>
                {
                    b.Property<int>("RoomDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomDbId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("RoomDbId");

                    b.HasIndex("RoomDbId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("GameServer.RoomPlayerDb", b =>
                {
                    b.Property<int>("RoomPlayerDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomPlayerDbId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("RoomDbId")
                        .HasColumnType("int");

                    b.HasKey("RoomPlayerDbId");

                    b.HasIndex("PlayerDbId")
                        .IsUnique();

                    b.HasIndex("RoomDbId", "PlayerDbId")
                        .IsUnique();

                    b.ToTable("RoomPlayer");
                });

            modelBuilder.Entity("GameServer.RoomPlayerDb", b =>
                {
                    b.HasOne("GameServer.PlayerDb", "Player")
                        .WithOne("RoomPlayer")
                        .HasForeignKey("GameServer.RoomPlayerDb", "PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.RoomDb", "Room")
                        .WithMany("RoomPlayers")
                        .HasForeignKey("RoomDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("GameServer.PlayerDb", b =>
                {
                    b.Navigation("RoomPlayer")
                        .IsRequired();
                });

            modelBuilder.Entity("GameServer.RoomDb", b =>
                {
                    b.Navigation("RoomPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
