pipeline {
    agent any
    environment {
        GIT_URI= "https://github.com/Sinminbeom/tetris.git"
        PROJECT_NAME = "tetris"
        DOCKER_TAG = "1.0.${currentBuild.number}"
        REMOTE_PATH= "project/infra_glue/${PROJECT_NAME}"
        REMOTE_SERVICE_PATH = "${REMOTE_PATH}/Server/Deploy"
        ENCRYPTION_KEY = credentials('ENCRYPTION_KEY')
    }
    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'main', name: 'BRANCH', type: 'PT_BRANCH', sortMode: 'DESCENDING_SMART', listSize: '5'
    }
    stages {
        stage('git clone') {
            steps {
                git branch: "${params.BRANCH}",
                url: "${GIT_URI}"
            }
        }
        stage('Docker build') {
            steps {
                sh "docker build -f ./Server/Deploy/Dockerfile -t ${PROJECT_NAME}:${DOCKER_TAG} ."

                sh "sed -i 's/<PROJECT_NAME>/${PROJECT_NAME}/g' ./Server/Deploy/docker-compose.yml"
                sh "sed -i 's/<BUILD_VER>/${DOCKER_TAG}/g' ./Server/Deploy/docker-compose.yml"
                sh "sed -i 's/<ENCRYPTION_KEY>/${ENCRYPTION_KEY}/g' ./Server/Deploy/docker-compose.yml"

            }
        }

        stage('Ssh transfer and docker restart') {
            steps{
                sshPublisher(publishers: [sshPublisherDesc(configName: 'oracle_cloud',
                transfers: [
                    sshTransfer(cleanRemote: false, excludes: '',
                    execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+',
                    remoteDirectory: "${REMOTE_SERVICE_PATH}",
                    remoteDirectorySDF: false,
                    removePrefix: "Server/Deploy",
                    sourceFiles: "Server/Deploy/docker-compose.yml") ,

                    sshTransfer(cleanRemote: false, excludes: '',
                    execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+',
                    execCommand: """
                        cd ${REMOTE_SERVICE_PATH}
                        echo \"docker-compose down\" >> jenkins.log
                        docker-compose down

                        echo \"docker-compose up -d\" >> jenkins.log
                        docker-compose up -d

                        echo \"depoly end\" >> jenkins.log

                        """)
                    ],
                    usePromotionTimestamp: false,
                    useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }    
}